CREATE EXTENSION IF NOT EXISTS "uuid-ossp"

INSERT INTO race(id,external_race_id,name) VALUES('1',uuid_generate_v4(),'DWARF')
INSERT INTO race(id,external_race_id,name) Values('2',uuid_generate_v4(),'ELF')
INSERT INTO race(id,external_race_id,name) VALUES('3',uuid_generate_v4(),'HUMAN')
INSERT INTO race(id,external_race_id,name) VALUES('4',uuid_generate_v4(),'HALF-ORC')
INSERT INTO race(id,external_race_id,name) VALUES('5',uuid_generate_v4(),'GOBLIN')
INSERT INTO race(id,external_race_id,name) VALUES('6',uuid_generate_v4(),'HOBGOBLIN')
INSERT INTO race(id,external_race_id,name) VALUES('7',uuid_generate_v4(),'ORC')
INSERT INTO race(id,external_race_id,name) VALUES('8',uuid_generate_v4(),'LIZARDFOLK')
INSERT INTO race(id,external_race_id,name) VALUES('9',uuid_generate_v4(),'CENTAUR')
INSERT INTO race(id,external_race_id,name) VALUES('10',uuid_generate_v4(),'MINOTAUR')

INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('1',uuid_generate_v4(),'FIGHTER')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('2',uuid_generate_v4(),'PALADIN')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('3',uuid_generate_v4(),'BARD')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('4',uuid_generate_v4(),'SORCERER')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('5',uuid_generate_v4(),'WARLOCK')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('6',uuid_generate_v4(),'CLERIC')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('7',uuid_generate_v4(),'RANGER')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('8',uuid_generate_v4(),'ROGUE')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('9',uuid_generate_v4(),'MONK')
INSERT INTO characterclass(id,external_character_class_id,name) VALUES ('10',uuid_generate_v4(),'WIZARD')

INSERT INTO cointype(id,external_coin_type_id,name) VALUES ('1',uuid_generate_v4(),'SILVER')
INSERT INTO cointype(id,external_coin_type_id,name) VALUES ('2',uuid_generate_v4(),'GOLD')
INSERT INTO cointype(id,external_coin_type_id,name) VALUES ('3',uuid_generate_v4(),'COPPER')